const API_URL="";const KEY="infinite-dungeon-v9";const D={N:[0,-1,'W','North','↑'],E:[1,0,'D','East','→'],S:[0,1,'S','South','↓'],W:[-1,0,'A','West','←']};
const monsters=[['Goblin Scout',1,'goblin'],['Cave Rat',1,'rat'],['Mine Spider',2,'spider'],['Skeleton',2,'skeleton'],['Kobold Trapper',2,'kobold'],['Basilisk',5,'basilisk'],['Medusa',6,'medusa'],['Dragon',10,'dragon'],['Skeleton King',9,'skeletonKing']];
const first=['Durin','Borin','Rurik','Thrain','Balin','Dwalin','Fundin','Brokk','Eitri','Thorin','Oin','Gloin'],beard=['Ironbeard','Stonebeard','Frostbeard','Ashbeard','Blackbeard','Greybeard','Longbeard','Redbeard','Goldbeard'];
const motives=['seek gold','restore a disgraced clan','find a missing relative','prove your worth to the guild','find a legendary weapon','follow a family map','seek glory','answer the call of the deep'];
const causes=['Miners have disappeared beneath the mountain','An ancient dwarven gate has opened','Strange bells have begun ringing underground','An abandoned mine has started producing ore again','A wounded messenger has returned from sealed tunnels','Voices have been heard beneath the mountain'];
const beliefs=['an ancient dwarven king has awakened','something is digging upward','the dead miners are not dead','an old enemy has returned','a forgotten mine has reopened','nobody knows what lies below'];const titles=['THE CALL OF THE DEEP','THE BLACK SEAL','THE BELLS OF IRONHOLD','THE FORGOTTEN VEIN'];
const rare=[['Skeleton King’s Bone Sword',7,'weapon','Its traits differ from king to king.',500],['Goblin Assassin’s Poison Dagger',5,'weapon','A lingering venom coats the edge.',420],['Dragon’s Ember Helm',8,'helmet','The metal remains warm.',650],['Basilisk-Eye Amulet',6,'amulet','It seems to notice hidden things.',550],['Medusa’s Gorgon Ring',6,'ring','Fear hesitates around its wearer.',600]];
const common=[['Rusty Sword',2,'weapon','',18],['Iron Axe',2,'weapon','',28],['Mine Pickaxe',1,'weapon','',12],['Leather Helm',1,'helmet','',15],['Chain Shirt',2,'body','',35],['Traveler’s Boots',1,'boots','',22],['Old Cape',1,'cape','',20],['Iron Ring',1,'ring','',16],['Miner’s Amulet',1,'amulet','',24],['Fine Dwarven Axe',4,'weapon','Balanced and dependable.',90]];
function r(n=20){return Math.floor(Math.random()*n)+1}function pick(a){return a[Math.floor(Math.random()*a.length)]}function ID(){return Math.random().toString(16).slice(2,6).toUpperCase()+'-'+Math.random().toString(16).slice(2,6).toUpperCase()}function save(){localStorage.setItem(KEY,JSON.stringify(S))}function num(v,d){return Number.isFinite(Number(v))?Number(v):d}
function newGame(){let title=pick(titles);return{hero:pick(first)+' '+pick(beard),expeditionId:ID(),expeditionTitle:title,opening:`${pick(causes)}. You descend to ${pick(motives)}. The elders suspect ${pick(beliefs)}.`,nickname:'',country:'',showCountry:false,setup:true,level:1,xp:0,hp:10,maxHp:10,floor:1,x:0,y:0,gold:0,stats:{int:1,str:1,cha:1,dex:1},rooms:{},logs:[],inventory:[],equipment:{amulet:null,helmet:null,body:null,boots:null,shoulders:null,legs:null,cape:null,rings:Array(10).fill(null)},fingers:Array(10).fill(true),rareLuck:0,startedAt:Date.now(),dead:false}}
function migrate(s){if(!s||typeof s!=='object')return newGame();s.level=Math.max(1,num(s.level,1));s.xp=Math.max(0,num(s.xp,0));s.maxHp=Math.max(10,num(s.maxHp,10));s.hp=Math.max(0,Math.min(s.maxHp,num(s.hp,s.maxHp)));s.floor=Math.max(1,num(s.floor,1));s.x=num(s.x,0);s.y=num(s.y,0);s.gold=Math.max(0,num(s.gold,0));s.stats=s.stats||{};for(const k of ['int','str','cha','dex'])s.stats[k]=Math.max(1,num(s.stats[k],1));s.rooms=s.rooms||{};s.logs=Array.isArray(s.logs)?s.logs:[];s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.nickname=(s.nickname||'').trim()||'Secret Hero';s.country=typeof s.country==='string'?s.country:'';s.showCountry=!!s.showCountry;s.equipment=s.equipment||{};s.equipment.rings=Array.isArray(s.equipment.rings)&&s.equipment.rings.length===10?s.equipment.rings:Array(10).fill(null);s.fingers=Array.isArray(s.fingers)&&s.fingers.length===10?s.fingers:Array(10).fill(true);s.setup=typeof s.setup==='boolean'?s.setup:false;s.expeditionId=s.expeditionId||ID();s.startedAt=s.startedAt||Date.now();return s}
function load(){try{return migrate(JSON.parse(localStorage.getItem(KEY)))}catch(e){return null}}let S=load()||newGame(),tradeOpen=false;
function key(){return`${S.floor}:${S.x},${S.y}`}function room(){if(!S.rooms[key()])S.rooms[key()]=gen();return S.rooms[key()]}
function gen(){let safe=S.floor===1&&S.x===0&&S.y===0;return{foe:safe?null:((Math.random()<.58)?monster():null),searched:false,exits:{N:null,E:null,S:null,W:null},ladderDown:Math.random()<.14,ladderUp:S.floor>1&&Math.random()<.18,npc:null,trader:null,rest:null,loot:null,secret:null}}
function monster(){let p=monsters.filter(m=>m[1]<=Math.max(2,S.floor+1));if(Math.random()<.06)p=monsters;let m=pick(p);let hp=m[1]*4+r(5);return{name:m[0],power:m[1],kind:m[2],hp,maxHp:hp,defeated:false}}
function exits(){let rm=room(),out=[];for(let d in D){if(rm.exits[d]===false)continue;let [dx,dy]=D[d],n=S.rooms[`${S.floor}:${S.x+dx},${S.y+dy}`],op={N:'S',S:'N',E:'W',W:'E'}[d];if(n&&n.exits[op]===false)continue;out.push(d)}return out}
function log(x,c=''){S.logs.unshift(`<div class="${c}">${x}</div>`);save();render()}function move(d){let rm=room();if(rm.foe&&!rm.foe.defeated)return log('⚔️ The foe blocks your path.','bad');if(!exits().includes(d))return log('That route is known to be blocked.');let [dx,dy]=D[d];S.x+=dx;S.y+=dy;room();save();render()}
function fight(){let f=room().foe;if(!f||f.defeated)return;let dmg=Math.max(1,S.stats.str+r(6));f.hp-=dmg;log(`You strike the ${f.name} for ${dmg}.`);if(f.hp<=0){f.hp=0;f.defeated=true;S.xp+=f.power*12;log(`🏆 You defeated the ${f.name}. The room is now safe to search.`,'good');level();save();render();return}let ed=Math.max(1,f.power+r(5)-S.stats.dex);S.hp-=ed;log(`The ${f.name} hits for ${ed}.`);if(S.hp<=0)die(`The ${f.name} defeats you.`)}
function level(){while(S.xp>=S.level*100){S.level++;S.maxHp+=2;S.hp=S.maxHp;let st=pick(['str','dex','int','cha']);S.stats[st]++;log(`✨ LEVEL UP! You reached level ${S.level}. ${st.toUpperCase()} rises. HP restored to ${S.hp}/${S.maxHp}.`,'gold')}}
function makeItem(a){return{name:a[0],power:a[1]+r(3)-1,slot:a[2],trait:a[3]||'A well-made piece of equipment.',value:a[4]||20}}
function loot(){let rareChance=.025+S.rareLuck*.015;if(Math.random()<rareChance){S.rareLuck=0;return makeItem(pick(rare))}S.rareLuck=Math.min(8,S.rareLuck+1);return makeItem(pick(common))}function foeLoot(kind){let x=rare.filter(a=>(kind==='skeletonKing'&&a[0].includes('Skeleton'))||(kind==='dragon'&&a[0].includes('Dragon'))||(kind==='basilisk'&&a[0].includes('Basilisk'))||(kind==='medusa'&&a[0].includes('Medusa')));if(Math.random()<.18+S.rareLuck*.02){S.rareLuck=0;return makeItem(pick(x.length?x:rare))}return loot()}
function addItem(i){if(S.inventory.length>=30){let drop=confirm(`Your pack is full. Destroy one carried item for ${i.name}? Cancel to abandon the new item.`);if(!drop)return false;let n=prompt('Enter the number of the carried item to destroy (1-'+S.inventory.length+')');let idx=num(n,0)-1;if(idx<0||idx>=S.inventory.length)return false;let old=S.inventory.splice(idx,1)[0];log(`🗑️ You destroy ${old.name}.`)}S.inventory.push(i);return true}
function search(){let rm=room();if(rm.foe&&!rm.foe.defeated)return log('You cannot search during combat.');if(rm.searched)return log('This room has already been searched.');rm.searched=true;let q=r(100);if(q<=10){rm.secret=pick(Object.keys(D));log(`🕳️ A secret passage is revealed to the ${D[rm.secret][3]}. Its compass arrow glows gold.`,'gold')}else if(q<=30){let i=loot();rm.loot=i;log(`🔎 You find ${i.name} in a cache.`,'good')}else if(q<=52){let i=loot();rm.loot=i;log(`🔎 You find ${i.name} in the room.`,'good')}else if(rm.foe&&rm.foe.defeated&&q<=78){let i=foeLoot(rm.foe.kind);rm.loot=i;log(`☠️ You find ${i.name} on the corpse of the ${rm.foe.name}.`,'rare')}else if(q<=85){rm.npc={name:pick(first)+' '+pick(beard),title:pick(['Keeper of the Blue Hall','Quest-Bearer','Lorewarden','Warden of Lost Things']),floor:S.floor};log(`🔵 You encounter ${rm.npc.name}, ${rm.npc.title}.`,'gold')}else if(q<=92){rm.trader=makeTrader();log(`💲 You encounter ${rm.trader.name}, ${rm.trader.title}.`,'gold')}else if(q<=97){rm.rest={uses:r(4)+1,heal:Math.max(2,Math.floor(S.maxHp*.35))};log('💚 You discover a source of rest. Its uses are known.','good')}else log('🔎 You find nothing useful.');save();render()}
function makeTrader(){let stock=[];for(let i=0;i<3;i++)stock.push(makeItem(Math.random()<.18?pick(rare):pick(common)));return{name:pick(first)+' '+pick(beard),title:pick(['the Merchant','the Trader','the Collector','the Gatherer','the Huntsman','Trading Master']),stock}}
function trade(){let t=room().trader;if(!t)return;tradeOpen=true;document.getElementById('trade').innerHTML=`<h2>💲 ${t.name} — ${t.title}</h2><p>Your gold: <b class="gold">${S.gold}</b></p><div class="tradegrid"><div><h3>Buy</h3>${t.stock.map((x,i)=>`<div class="item"><b>${x.name}</b><br>Power +${x.power} · ${x.value}g<br><span class="small">${x.trait}</span><br><button onclick="buy(${i})" ${S.gold<x.value||S.inventory.length>=30?'disabled':''}>Buy</button></div>`).join('')}</div><div><h3>Sell</h3>${S.inventory.length?S.inventory.map((x,i)=>`<div class="item"><b>${x.name}</b><br>${Math.max(1,Math.floor(x.value*.5))}g<br><button onclick="sell(${i})">Sell permanently</button></div>`).join(''):'Nothing to sell.'}</div></div><button onclick="tradeOpen=false;render()">Leave trade</button>`}
function buy(i){let t=room().trader,x=t.stock[i];if(!x||S.gold<x.value||S.inventory.length>=30)return;S.gold-=x.value;S.inventory.push({...x});t.stock.splice(i,1);log(`💲 You bought ${x.name} for ${x.value} gold.`,'good');save();trade();render()}function sell(i){let x=S.inventory[i];if(!x)return;let v=Math.max(1,Math.floor(x.value*.5));if(!confirm(`Sell ${x.name} for ${v} gold? There is no buyback.`))return;S.inventory.splice(i,1);S.gold+=v;log(`💲 You sold ${x.name} for ${v} gold. It is gone permanently.`,'good');save();trade();render()}
function rest(){let rm=room();if(rm.foe&&!rm.foe.defeated)return log('You cannot rest during combat.');if(!rm.rest||rm.rest.uses<=0)return log('There is nowhere safe to rest here.');rm.rest.uses--;S.hp=Math.min(S.maxHp,S.hp+rm.rest.heal);log(`💚 You recover ${rm.rest.heal} HP. HP ${S.hp}/${S.maxHp}.`,'good');if(!rm.rest.uses){rm.rest=null;log('💚 The source is depleted.')}save();render()}
function ladder(dir){let rm=room();if(rm.foe&&!rm.foe.defeated)return log('You must defeat the foe first.');if(dir==='down'&&rm.ladderDown){S.floor++;S.x=0;S.y=0;room();log('🪜 You descend deeper.','gold')}else if(dir==='up'&&rm.ladderUp){S.floor=Math.max(1,S.floor-1);S.x=0;S.y=0;room();log('🪜 You ascend to the remembered floor.','gold')}save();render()}
function useF(){let rm=room();if(rm.foe&&!rm.foe.defeated)return log('You cannot interact while fighting.');if(rm.ladderDown)return ladder('down');if(rm.ladderUp)return ladder('up');if(rm.trader)return trade();if(rm.npc)return log(`🔵 You speak with ${rm.npc.name}.`,'gold');if(rm.rest)return rest();log('There is no special interaction here.')}
function flee(){let f=room().foe;if(!f||f.defeated)return;let roll=r();if(roll===20)return log('🏃 LEGENDARY ESCAPE! You flee without consequence.','gold');let success=r(100)<=Math.min(90,35+S.stats.dex*5);if(success){let e=r(3);if(e===1){S.hp=Math.max(1,S.hp-2);log('🏃 You escape, but suffer damage.','bad')}else if(e===2){S.stats.dex=Math.max(1,S.stats.dex-1);log('🏃 You escape shaken. DEX falls by 1.','bad')}else log(`🏃 You escape the ${f.name}.`,'good');save();render();return}if(f.kind==='basilisk'){S.hp-=1;log('☠️ Basilisk venom burns through you.','bad')}else if(f.kind==='dragon'){S.hp-=3;log('🔥 Dragon fire catches you.','bad')}else if(f.kind==='medusa'){S.stats.cha=Math.max(1,S.stats.cha-1);log('😨 Medusa leaves you terrified. CHA falls by 1.','bad')}else{S.hp-=2;log(`⚔️ The ${f.name} stops your escape.`,'bad')}if(S.hp<=0)die('Your attempt to flee proves fatal.');else{save();render()}}
function die(x){S.dead=true;log(`☠️ ${x} The expedition ends here.`,'bad');if(API_URL)fetch(API_URL+'/expedition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expedition_id:S.expeditionId,hero_name:S.hero,nickname:S.nickname||'Secret Hero',show_country:S.showCountry,country:S.country,expedition_name:S.expeditionTitle,level:S.level,floor:S.floor,total_xp:S.xp,inventory_count:S.inventory.length,death_cause:x,started_at:S.startedAt})}).catch(()=>{});save();render()}
function begin(){S.nickname=(document.getElementById('nick').value||'').trim()||'Secret Hero';S.country=(document.getElementById('country').value||'').trim();S.showCountry=document.getElementById('showCountry').checked;S.setup=false;log(`⛏️ ${S.hero} enters the dungeon under the name ${S.nickname}.`,'gold');save();render()}
function render(){let rm=room();document.getElementById('identity').innerHTML=`<b>${S.hero}</b> · <i>${S.expeditionTitle}</i>`;document.getElementById('intro').innerHTML=S.setup?`<h2>${S.expeditionTitle}</h2><p>${S.opening}.</p><div class="field"><label>Nickname (optional): <input id="nick" maxlength="24" placeholder="Secret Hero"></label></div><div class="field"><label>Country (optional): <input id="country" maxlength="40" placeholder="e.g. Sweden"></label></div><div class="field"><label><input id="showCountry" type="checkbox"> Show my country in the Global Hall</label></div><button onclick="begin()">Begin the descent</button>`:`<span class="small">The mountain closes behind you. The expedition continues.</span>`;document.getElementById('status').innerHTML=`❤️ ${S.hp}/${S.maxHp} · ⚒️ Lv ${S.level} · XP ${S.xp} · Floor ${S.floor} · 💰 ${S.gold} · 🎒 ${S.inventory.length}/30<br><span class="small">INT ${S.stats.int} · STR ${S.stats.str} · CHA ${S.stats.cha} · DEX ${S.stats.dex}</span>`;let f=rm.foe&&!rm.foe.defeated?`<div>⚔️ <b>${rm.foe.name}</b> — ${rm.foe.hp}/${rm.foe.maxHp} HP</div>`:rm.foe?`<div>☠️ ${rm.foe.name} — defeated</div>`:'';document.getElementById('room').innerHTML=`<h2>Chamber</h2>${f}${rm.loot?`<div>🎁 ${rm.loot.name} · +${rm.loot.power}</div>`:''}${rm.ladderDown?'<div>🟢 ↓ Ladder down</div>':''}${rm.ladderUp?'<div>🟢 ↑ Ladder up</div>':''}${rm.npc?`<div>🔵 ${rm.npc.name}, ${rm.npc.title}</div>`:''}${rm.trader?`<div>💲 ${rm.trader.name}, ${rm.trader.title}</div>`:''}${rm.rest?`<div>💚 Rest source: ${rm.rest.uses} uses</div>`:''}`;let fightNow=rm.foe&&!rm.foe.defeated;let html=fightNow?`<button onclick="fight()">⚔️ Fight</button><button onclick="flee()">🏃 Flee</button>`:`<button onclick="search()" ${rm.searched?'disabled':''}>🔎 Search</button><div class="compass"><span></span><button onclick="move('N')">↑ W</button><span></span><button onclick="move('W')">← A</button><button onclick="useF()">F</button><button onclick="move('E')">→ D</button><span></span><button onclick="move('S')">↓ S</button><span></span></div>${rm.ladderDown?'<button onclick="ladder(\'down\')">↓ Descend</button>':''}${rm.ladderUp?'<button onclick="ladder(\'up\')">↑ Ascend</button>':''}${rm.trader?'<button onclick="trade()">💲 Trade</button>':''}${rm.npc?'<button onclick="useF()">🔵 Talk</button>':''}${rm.rest?'<button onclick="rest()">💚 Rest</button>':''}`;html+=`<hr><button onclick="newRun()">New Run</button>`;document.getElementById('actions').innerHTML=html;document.getElementById('trade').innerHTML=tradeOpen&&rm.trader?'': '';if(tradeOpen&&rm.trader)trade();document.getElementById('log').innerHTML=S.logs.join('');document.getElementById('hall').innerHTML=`<h2>🏆 Global Hall</h2><div class="small">Public tag: <b>${S.nickname||'Secret Hero'}</b>${S.showCountry&&S.country?' · '+S.country:''}</div>`}
function newRun(){if(!confirm('Start a completely new expedition? This cleanses the old run and logs.'))return;localStorage.removeItem(KEY);S=newGame();tradeOpen=false;render()}
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;let k=e.key.toLowerCase();if(k==='w')move('N');if(k==='a')move('W');if(k==='s')move('S');if(k==='d')move('E');if(k==='f')useF()});save();render();
