const KEY="infinite-dungeon-v13";
const dwarves=["Durin Ironbeard","Borin Deepaxe","Kargan Stonepick","Thorin Mountainbeard","Dwalin Blackforge","Farin Axebreaker","Balin Goldvein","Gorin Redhammer"];
const intros=["The old miners spoke of a sealed kingdom beneath the mountains. You entered to discover what survived below.","A forgotten royal expedition vanished beneath the mountain. You descend to learn their fate.","A tremor opened an ancient shaft, and rumors of lost Dwarven treasures followed."];
const types=["weapon","helmet","armor","boots","shoulders","trousers","cape","amulet","ring"];
const names={weapon:["Rusty Sword","Deepforge Axe","Skeleton King's Bone Sword","Goblin Assassin's Poison Dagger"],helmet:["Iron Helm","Dragon's Helmet","Bone Helm"],armor:["Old Mail","Deepplate"],boots:["Miner Boots","Swift Boots"],shoulders:["Iron Pauldrons"],trousers:["Leather Trousers"],cape:["Traveler's Cape","Shadowweave Cape","Dragon Cape"],amulet:["Stone Amulet","Moon Amulet"],ring:["Iron Ring","Moonstone Ring","Bone Ring","Ember Ring","Dwarven Signet"]};
const arts={weapon:["⚔️","🪓","🗡️"],helmet:["🪖","🐉","💀"],armor:["🛡️","🥋"],boots:["🥾","👢"],shoulders:["🛡️","⚔️"],trousers:["👖"],cape:["🧥","🦇"],amulet:["📿","🔮"],ring:["💍","💎","🔴","🔵","🟡","⚪","🟢","🟣","🪨","✨"]};
const rar=["common","uncommon","rare","mythical"], dep=["bronze","silver","gold","titan","glowing"];
let S=JSON.parse(localStorage.getItem(KEY)||"null")||fresh();

function fresh(){return{name:dwarves[Math.floor(Math.random()*dwarves.length)],nickname:"",level:1,xp:0,hp:10,maxHp:10,floor:1,x:0,y:0,gold:0,stats:{str:1,dex:1,int:1,cha:1},rooms:{"1:0:0":{searched:false,blocked:{},enemy:null,ladder:null,secret:null}},inventory:[],equipment:{weapon:null,helmet:null,armor:null,boots:null,shoulders:null,trousers:null,cape:null,amulet:null,rings:Array(10).fill(null)},quests:[],log:[`📖 ${intros[Math.floor(Math.random()*intros.length)]}`]}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function key(){return`${S.floor}:${S.x}:${S.y}`}
function room(){return S.rooms[key()]||(S.rooms[key()]={searched:false,blocked:{},enemy:null,ladder:null,secret:null})}
function d20(){return 1+Math.floor(Math.random()*20)}
function msg(t){S.log.unshift(t);S.log=S.log.slice(0,100);save();render()}
function makeItem(type){let z=Math.random(),r=z<.65?0:z<.90?1:z<.985?2:3,p=["str","dex","int","cha"],i={id:crypto.randomUUID(),type,name:names[type][Math.floor(Math.random()*names[type].length)],rarity:rar[r],depth:dep[Math.min(4,Math.floor((S.floor-1)/10))],art:arts[type][Math.floor(Math.random()*arts[type].length)],stats:{},trait:null},a=p[Math.floor(Math.random()*4)];i.stats[a]=Math.max(1,Math.round((1+S.floor*.8+S.level*.7)*(.6+Math.random())));if(Math.random()<.55)i.stats[p[Math.floor(Math.random()*4)]]=1+Math.floor(Math.random()*Math.max(1,S.floor/5));if(Math.random()<.18+r*.12)i.trait=["Bone Rend","Grave Fortune","Dragonblood","Veilstep","Deep Luck","Poison Edge"][Math.floor(Math.random()*6)];return i}
function slot(i){return i.type==="ring"?"rings":i.type}
function obtain(i){let s=slot(i);if(s==="rings"){let n=S.equipment.rings.findIndex(x=>!x);if(n>=0){S.equipment.rings[n]=i;return`💍 ${i.name} auto-equipped.`}}else if(!S.equipment[s]){S.equipment[s]=i;return`⚔️ ${i.name} auto-equipped.`}if(S.inventory.length<30){S.inventory.push(i);return`🎒 ${i.name} added to extra inventory.`}return`⚠️ Inventory full; ${i.name} must be discarded.`}
function item(i,inv){return`<div class="item ${i.rarity} ${i.depth}"><span class="art">${i.art}</span><b>${i.name}</b><div>${Object.entries(i.stats).map(([k,v])=>`+${v} ${k.toUpperCase()}`).join(" · ")}</div>${i.trait?`<div>Trait: ${i.trait}</div>`:""}<div class="small">${i.rarity} · ${i.depth}</div>${inv?`<button onclick="equip('${i.id}')">Equip</button>`:""}</div>`}
function equip(id){let n=S.inventory.findIndex(i=>i.id===id);if(n<0)return;let i=S.inventory[n],s=slot(i);if(s==="rings"){let f=S.equipment.rings.findIndex(x=>!x);if(f<0)return msg("💍 No free finger.");S.equipment.rings[f]=i;S.inventory.splice(n,1)}else{let old=S.equipment[s];S.equipment[s]=i;if(old)S.inventory[n]=old;else S.inventory.splice(n,1)}save();render()}
function damage(n){S.hp=Math.max(0,S.hp-n);if(S.hp===0){S.hp=0;msg("☠️ HP reached 0. The expedition has ended.");}else render()}
function spawn(){let early=["Rat","Rat","Rat","Rat","Goblin Assassin","Goblin Assassin","Skeleton King","Basilisk","Medusa"],late=["Rat","Goblin Assassin","Skeleton King","Basilisk","Medusa","Dragon"];let pool=S.floor<=10?early:late;let n=pool[Math.floor(Math.random()*pool.length)];if(Math.random()<0.01)n="Dragon";return{name:n,hp:5+Math.round(S.floor*1.8)}}
function search(){let r=room();if(r.enemy&&r.enemy.hp>0)return msg("⚔️ Search is unavailable during combat.");if(r.searched)return;r.searched=true;let q=Math.random();if(q<.15){r.secret={dir:["N","E","S","W"][Math.floor(Math.random()*4)]};msg("✨ A secret passage is revealed.");return}if(q<.42){let i=makeItem(types[Math.floor(Math.random()*types.length)]);msg(`🎁 ${i.name} found. ${obtain(i)}`);return}if(q<.55){msg("⚠️ A hidden trap strikes.");damage(Math.max(1,d20()%4));return}msg("🔎 You find nothing.")}
function move(d){let r=room();if(r.blocked[d])return;if(r.enemy&&r.enemy.hp>0)return msg("⚔️ A foe blocks the way.");let opp={N:"S",S:"N",E:"W",W:"E"}[d],dx=d==="E"?1:d==="W"?-1:0,dy=d==="S"?1:d==="N"?-1:0,nk=`${S.floor}:${S.x+dx}:${S.y+dy}`,nr=S.rooms[nk];if(nr&&nr.blocked[opp]){r.blocked[d]=true;save();return msg("🚫 That route is known to be closed.")}S.x+=dx;S.y+=dy;let x=room();if(!(S.floor===1&&S.x===0&&S.y===0)&&!x.enemy&&!x.searched&&Math.random()<.28)x.enemy=spawn();save();render()}
function fight(){let r=room();if(!r.enemy||r.enemy.hp<=0)return;let hit=d20();if(hit===1){msg(`💥 Critical miss! ${r.enemy.name} counterattacks.`);damage(Math.max(1,d20()%5+1));return}let n=Math.max(1,d20()%6+Math.floor(S.stats.str/10));r.enemy.hp=Math.max(0,r.enemy.hp-n);if(r.enemy.hp===0){let defeated=r.enemy.name;r.enemy=null;msg(`☠️ ${defeated} is defeated. The way is open.`)}else{msg(`⚔️ You hit ${r.enemy.name} for ${n}.`);damage(Math.max(1,d20()%6))}}
function flee(){let r=room();if(!r.enemy||r.enemy.hp<=0)return;let n=d20();if(n===20)return msg("🏃 Critical escape! No consequence.");if(n<=4){msg("🏃 Failed escape! The foe counterattacks.");damage(Math.max(1,d20()%5+1));return}if(n<=9){msg("🏃 You escape but take damage.");damage(Math.max(1,d20()%4+1));return}if(n<=13){msg("🏃 You escape but suffer a lingering consequence.");damage(1);return}msg("🏃 You escape successfully.")}
function act(a){if(S.hp<=0)return;if(a==="search")search();else if(a==="fight")fight();else if(a==="flee")flee();else if(["N","S","E","W"].includes(a))move(a);else if(a==="down"){S.floor++;S.x=0;S.y=0;room();msg(`🟨 You descend to floor ${S.floor}.`)}else if(a==="up"&&S.floor>1){S.floor--;S.x=0;S.y=0;room();msg(`🟩 You ascend to floor ${S.floor}.`)}save();render()}
function newRun(){localStorage.removeItem(KEY);S=fresh();render()}
function drawMap(){let minX=S.x-5,maxX=S.x+5,minY=S.y-5,maxY=S.y+5,out=[];for(let y=minY;y<=maxY;y++){let row=[];for(let x=minX;x<=maxX;x++){let r=S.rooms[`${S.floor}:${x}:${y}`];if(x===S.x&&y===S.y)row.push("◎");else if(!r)row.push("  ");else if(r.secret)row.push("✦");else if(r.ladder==="down")row.push("↓");else if(r.ladder==="up")row.push("↑");else if(r.enemy&&r.enemy.hp>0)row.push("⚔");else row.push("·")}out.push(row.join(" "));}return out.join("\\n")}
function render(){let r=room();intro.textContent=`${S.name} · Floor ${S.floor}`;stats.innerHTML=[`❤️ HP ${Math.max(0,S.hp)}/${S.maxHp}`,`⭐ Level ${S.level}`,`XP ${S.xp}`,`STR ${S.stats.str}`,`DEX ${S.stats.dex}`,`INT ${S.stats.int}`,`CHA ${S.stats.cha}`,`💰 ${S.gold}`].map(x=>`<div>${x}</div>`).join("");roomTitle.textContent=`Floor ${S.floor} — Chamber`;roomText.textContent=r.enemy&&r.enemy.hp>0?`⚔️ ${r.enemy.name} blocks the chamber.`:"The chamber is quiet.";map.textContent=drawMap();actions.innerHTML=r.enemy&&r.enemy.hp>0?`<button onclick="act('fight')">⚔️ Fight</button><button onclick="act('flee')">🏃 Flee</button>`:`<button onclick="act('N')">W · North</button><button onclick="act('W')">A · West</button><button onclick="act('S')">S · South</button><button onclick="act('E')">D · East</button>${r.searched?"":`<button onclick="act('search')">🔎 Search</button>`}${r.ladder?`<button onclick="act('${r.ladder}')">🪜 ${r.ladder==="down"?"↓ Descend":"↑ Ascend"}</button>`:""}`;if(S.hp<=0)actions.innerHTML="☠️ Dead — press New Run.";log.innerHTML=S.log.map(x=>`<div>${x}</div>`).join("");equipment.innerHTML=["weapon","helmet","armor","boots","shoulders","trousers","cape","amulet"].map(k=>`<div class=card><b>${k.toUpperCase()}</b>${S.equipment[k]?item(S.equipment[k]):"<div class=small>Empty</div>"}</div>`).join("")+`<div class=card><b>RINGS</b><div class=grid>${S.equipment.rings.map((x,i)=>x?item(x):`<div class=item>${i+1}. Empty</div>`).join("")}</div></div>`;inventory.innerHTML=S.inventory.length?S.inventory.map(x=>item(x,true)).join(""):"<div class=small>Empty</div>";quests.innerHTML=S.quests.length?S.quests.map(q=>`<div class=card>${q.found?"✅":"🔎"} ${q.itemName}</div>`).join(""):"<div class=small>No active quests.</div>";let h=JSON.parse(localStorage.getItem("infiniteDungeonHall")||"[]");hall.innerHTML=h.slice(0,10).map(x=>`<div class=card><b>${x.nickname||"Secret Hero"}</b> — ${x.name}<br>XP ${x.xp} · Level ${x.level} · Floor ${x.floor} · Items ${x.items}</div>`).join("")||"<div class=small>No completed expeditions yet.</div>"}
window.act=act;window.equip=equip;window.newRun=newRun;render();