name = "infinite-dungeon-api"
main = "worker.js"
compatibility_date = "2026-08-25"

[[d1_databases]]
binding = "DB"
database_name = "infinite-dungeon"
database_id = "6651a970-0417-4e4d-ba64-29a757a8a35a"
